#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  custom:
    manual run junit report:
      - step:
            runs-on:
              - self.hosted
              - windows
            script:
              - dotnet clean
              - dotnet restore
              - cd si-automated-tests
              - dotnet add package JUnitTestLogger --version 1.1.0
              - dotnet test --logger:"junit" -s test.runsettings
    manual run trx report:
      - step:
            runs-on:
              - self.hosted
              - windows
            script:
              - dotnet clean
              - dotnet restore
              - cd si-automated-tests
              - dotnet test --logger:"trx;LogFileName=../../TestResults/TestOutput.trx" -s test.runsettings
            after-script:
              - set PATH="{$env:PATH}:/root/.dotnet/tools"
              - trx2junit ./TestResults/*.trx
              
  default:
    - parallel:
        - step:
            name: Build
            caches:
              - dotnetcore
            script:
              - dotnet restore
              - dotnet build --no-restore
        - step:
            name: Test
            trigger: manual
            caches:
              - dotnetcore
            script:
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - cd si-automated-tests
              - dotnet test --no-build --test-adapter-path:. --logger:"trx;LogFilePath=$REPORTS_PATH/TestOutput.xml" -s test.runsettings
        - step:
            name: Lint the code
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=si-automated-tests
              - export REPORTS_PATH=linter-reports
              - dotnet new tool-manifest
              - dotnet tool install JetBrains.ReSharper.GlobalTools
              - dotnet tool restore
              - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
            artifacts:
              - linter-reports/**
